ln -s ~/github-repos/Landotfiles/Desktop/shell/.zshrc ~/.zshrc
ln -s ~/github-repos/Landotfiles/Desktop/alacritty ~/.config/alacritty
ln -s $HOME/github-repos/Landotfiles/Desktop/wofi $HOME/.config/wofi
ln -s $HOME/github-repos/Landotfiles/Desktop/cava $HOME/.config/cava
ln -s $HOME/github-repos/Landotfiles/Desktop/waybar $HOME/.config/waybar
ln -s $HOME/github-repos/Landotfiles/Desktop/hypr $HOME/.config/hypr
ln -s $HOME/github-repos/Landotfiles/Desktop/swaync $HOME/.config/swaync
ln -s $HOME/github-repos/Landotfiles/Desktop/swaylock $HOME/.config/swaylock
ln -s $HOME/github-repos/Landotfiles/Desktop/kitty $HOME/.config/kitty
ln -s $HOME/github-repos/Landotfiles/Desktop/misc/.devenvs $HOME